### ISSUE TITLE
Improve Google & GTMetrix scores

### ISSUE THREAD

**Issue by raullopezgn** [akinuri/js-lib#1] opened 2021-04-24 07:07 UTC
Hi, I'm using the Newspaper theme in Wordpress and they are using you js-lib.

I have been performing optimization tests and both Google and GTMetrix recommends use passive listeners. I share with you 2 links to both tests:
https://developers.google.com/speed/pagespeed/insights/?hl=es&url=https%3A%2F%2Fwww.iphonedigital.com%2Fcomo-borrar-espacio-google-maps-cache-iphone-ipad%2F
https://gtmetrix.com/reports/www.iphonedigital.com/jRHj16yy/

I was testing the following page and GTMetrix mention that it can fixed at line 127:
https://www.iphonedigital.com/como-borrar-espacio-google-maps-cache-iphone-ipad/

You know better than me how to fix it and if you update the repository after doing that, it will be aumatically fixed in many, many webistes. Thank you in advance @akinuri

**Comment by akinuri** [comment] 2021-04-24 18:12
I suppose you're referring to the `EventListener.js` file. I haven't used it it a long time. I'm surprised it's in production code :)

In one of the sites you posted, it says:

> Use passive listeners to improve scrolling performance

It also provides a solution to the issue:

> Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance.

You can read more about this at [Improving scrolling performance with passive listeners (MDN)](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners).
Also a StackOverflow question: [What are passive event listeners?](https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners).

Therefore, I don't think this issue/warning is about `EventListener.js` library. The library does not make any changes to the added listeners/callbacks. It just logs them. I believe the issue is about the WordPress theme. The theme should mark the scroll related event listeners as passive. 

When I inspect the `EventListeners` object in the page you posted, e.g., I see:

    7: EventListener {target: document, type: "touchmove", options: null, useCapture: false, callback: ƒ, …}
    20: EventListener {target: a#cancel-comment-reply-link, type: "touchstart", options: null, useCapture: null, callback: ƒ, …}

These listeners should have been marked as passive, i.e.:

    7: EventListener {target: document, type: "touchmove", options: {passive: true}, useCapture: false, callback: ƒ, …}

So, I suggest you contact the theme author about this issue. You can just direct him/her to this issue, if you don't want to repeat yourself. I don't plan on deleting this.

**Comment by akinuri** [comment] 2021-06-03 17:13
While I'm checking another issue related to this script, thought I should check on this one too. Have you solved your problem yet?

I'll be closing this soon.

**Closed as completed** 2021-07-18 18:38 UTC
